### ISSUE TITLE
Is `SProxy` still a thing?

### ISSUE THREAD

**Issue by JamieBallingall** [thomashoneyman/writing#10]
I was working through "Practical Profunctor Lenses & Optics In PureScript" and had trouble with:
```
_name :: forall a r. Lens' { name :: a | r } a
_name = prop (SProxy :: SProxy "name")
```
`SProxy` doesn't appear in Pursuit and I believe that it was replaced with a polymorphic `Proxy` in `purs` 0.14.

I think that every occurance of `SProxy` could be replaced with `Proxy` but I'm not confident enough in that to hit you with a PR out of the blue. But I am happy to generate a PR if that is the solution.

**Comment by thomashoneyman** [comment]
Good catch! Indeed there is only the one Proxy type now and they can all be replaced.
